name: putone
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # LocalDatabase
  shared_preferences:

  # Riverpod
  flutter_hooks:
  hooks_riverpod:

  # Entity
  freezed_annotation:
  json_annotation:
  equatable:

  # Launcher
  url_launcher:

  # Image
  image_picker:
  flutter_svg:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_remote_config: ^4.2.3

  # Api
  retrofit:
  dio:

  # Other
  uuid:
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed: ^2.3.5
  retrofit_generator:

  # Other
  flutter_launcher_icons:
  blur: ^3.1.0

flutter:
  assets:
    - assets/images/
    - assets/svgs/

  uses-material-design: true
